### ISSUE TITLE
Inquiry on Accessing Pre-trained Models and Pre-processed Data for MOFDiff Study

### ISSUE THREAD

**Issue by Xuwznln** [microsoft/MOFDiff#13]
I read your article titled "MOFDiff: Coarse-grained Diffusion for Metal-Organic Framework Design" published at ICLR 2024, and found myself deeply intrigued by the work of your team. I am particularly interested in this generative model and would love to have the opportunity to hands-on try and further study this method.

I noticed that you have provided links to pre-trained models and pre-processed data on GitHub, but unfortunately, I found that access requires permission. Therefore, I am reaching out to inquire whether it would be possible to gain access to these resources, allowing me to gain a deeper understanding of your work and explore its applications.

Thank you very much for considering my request.

**Comment by kyonofx** [comment]
Thank you for your interest, can you try this link?

https://zenodo.org/records/10806179

**Comment by Xuwznln** [comment]
I've successfully accessed the link and everything appears to be in order. Thank you for your response.
